# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VoiceAssistantGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import QObject
from PyQt5.QtGui import QTextCursor
from PyQt5.QtWidgets import QApplication, QTextEdit
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainGUI(object):
    def setupUi(self, mainGUI):
        mainGUI.setObjectName("Jarvis")
        mainGUI.resize(1043, 587)
        mainGUI.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.titlr = QtWidgets.QLabel(mainGUI)
        self.titlr.setGeometry(QtCore.QRect(330, 0, 391, 81))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(111)
        font.setBold(True)
        self.titlr.setFont(font)
        self.titlr.setText("")
        self.titlr.setPixmap(QtGui.QPixmap("D:\\Project III Year\\GUI\\B.G\\20231026_142459.png"))
        self.titlr.setScaledContents(True)
        self.titlr.setObjectName("titlr")
        self.startbutton = QtWidgets.QPushButton(mainGUI)
        self.startbutton.setGeometry(QtCore.QRect(0, 30, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(22)
        self.startbutton.setFont(font)
        self.startbutton.setStyleSheet("image: url(D:/Project III Year/GUI/B.G/Start.png);")
        self.startbutton.setText("")
        self.startbutton.setObjectName("startbutton")
        self.reactor = QtWidgets.QLabel(mainGUI)
        self.reactor.setGeometry(QtCore.QRect(450, 80, 291, 221))
        self.reactor.setText("")
        self.reactor.setPixmap(QtGui.QPixmap("D:\\Project III Year\\GUI\\B.G\\Siri"))
        self.reactor.setScaledContents(True)
        self.reactor.setObjectName("reactor")
        self.stopbutton = QtWidgets.QPushButton(mainGUI)
        self.stopbutton.setGeometry(QtCore.QRect(0, 110, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(20)
        self.stopbutton.setFont(font)
        self.stopbutton.setStyleSheet("image: url(D:/Project III Year/GUI/B.G/Quit.png);")
        self.stopbutton.setText("")
        self.stopbutton.setObjectName("stopbutton")
        self.earth = QtWidgets.QLabel(mainGUI)
        self.earth.setGeometry(QtCore.QRect(250, 90, 231, 181))
        self.earth.setText("")
        self.earth.setPixmap(QtGui.QPixmap("D:\\Project III Year\\GUI\\B.G\\Earth.gif"))
        self.earth.setScaledContents(True)
        self.earth.setObjectName("earth")
        self.graph = QtWidgets.QLabel(mainGUI)
        self.graph.setGeometry(QtCore.QRect(200, 300, 531, 271))
        self.graph.setText("")
        self.graph.setPixmap(QtGui.QPixmap("D:\\Project III Year\\GUI\\B.G\\Hero_Template.gif"))
        self.graph.setScaledContents(True)
        self.graph.setObjectName("graph")
        self.bg = QtWidgets.QLabel(mainGUI)
        self.bg.setGeometry(QtCore.QRect(-30, 0, 1071, 591))
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap("D:\\Project III Year\\GUI\\B.G\\vecteezy_technology-background-video-4k-hd-resolution_22653051_155.gif"))
        self.bg.setScaledContents(True)
        self.bg.setObjectName("bg")
        self.area = QtWidgets.QPlainTextEdit(mainGUI)
        self.area.setGeometry(QtCore.QRect(740, 120, 301, 451))
        self.area.setObjectName("area")
        # self.area.setReadOnly(True)
        self.area.setStyleSheet('color:white')
        self.area.setPlainText("")
        self.area.setOverwriteMode(True)
        self.area.setStyleSheet('color: white')
        self.outputtitle = QtWidgets.QLabel(mainGUI)
        self.outputtitle.setGeometry(QtCore.QRect(740, 80, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(20)
        self.outputtitle.setFont(font)
        self.outputtitle.setObjectName("outputtitle")
        self.outputtitle.setStyleSheet('color: white')
        self.bg.raise_()
        self.titlr.raise_()
        self.startbutton.raise_()
        self.reactor.raise_()
        self.stopbutton.raise_()
        self.earth.raise_()
        self.graph.raise_()
        self.area.raise_()
        self.outputtitle.raise_()

        self.retranslateUi(mainGUI)
        QtCore.QMetaObject.connectSlotsByName(mainGUI)

    def retranslateUi(self, mainGUI):
        _translate = QtCore.QCoreApplication.translate
        mainGUI.setWindowTitle(_translate("Jarvis", "Jarvis"))
        self.area.setPlaceholderText(_translate("mainGUI","Output"))
        self.outputtitle.setText(_translate("mainGUI", "  Output:"))
        mainGUI.setFixedSize(mainGUI.size())
import GUI


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainGUI = QtWidgets.QWidget()
    ui = Ui_mainGUI()
    ui.setupUi(mainGUI)
    mainGUI.show()
    sys.exit(app.exec_())
